### PR TITLE
Update to support 5.6, tests also pass

### PR DESCRIPTION
**Pull request by adamdburton**

### CODE REVIEW

**Comment by adamdburton** [comment]
Done, 7.1.3 and 7.2 passing :)

**Comment by rydurham** [comment]
Thank you!   One more tweak and then I think we are good to go:  let's bump up the minimum required PHP version in the `composer.json` file to "^7.1.3" to match Laravel 5.6.

**Comment by rydurham** [comment]
Thank you!

**Comment by rydurham** [comment]
This has now been tagged as version 2.2.   Much appreciated!

**Pull request merged**
